sudo: required
services:
    - docker

before_install:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t dockertrainingarun/wm10customimage -f ./webmethods/Dockerfile .

install:
    - docker run --rm -d -p 2323:5555/tcp dockertrainingarun/wmmicroimage
    - docker ps

before_script:
    - sleep 151

script:
    - docker ps
    - docker run -t postman/newman_ubuntu1404 run "https://www.getpostman.com/collections/7a621e2f033748c005a1"

after_success:
    - docker build -t dockertrainingarun/ngnixwmcustom -f ./nginx/Dockerfile.dev .
#tag the images built
    - docker tag dockertrainingarun/ngnixwmcustom dockertrainingarun/ngnixwmcustom:v1
    - docker tag dockertrainingarun/wmmicroimage dockertrainingarun/wmmicroimage:v1

#push image to docker hub
    - docker push dockertrainingarun/wm10customimage:v1
    - docker push dockertrainingarun/ngnixwmcustom:v1