sudo: required
services:
    - docker

before_install:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t dodkerdemorepo -f Dockerfile.dev .

install:
    - docker run --rm -d -p 2323:5555/tcp dodkerdemorepo:latest
    - docker ps

before_script:
    - sleep 152

script:
    - docker ps
    - docker run -t postman/newman_ubuntu1404 run "https://www.getpostman.com/collections/7a621e2f033748c005a1"

deploy:
    provider: script
# specify the deployment script
    script: bash deploy.sh
# specify to deploy with code change a given branch
    on:
       branch: master