apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mysql-server
  template:
    metadata:
      labels:
        component: mysql-server
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: manage
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim