apiVersion: v1
kind: Service
metadata:
  name: mysql-clusterip-service
spec:
  selector:
    component: mysql-server
  type:  NodePort
  ports:
    - port: 3306
      nodePort: 31100
      targetPort: 3306