apiVersion: v1
kind: Service
metadata:
  name: webmethods-cluster-ip-service
spec:
  selector:
    component: webmethods-is 
  type:  NodePort
  ports:
    - port: 8443
      nodePort: 31000
      targetPort: 5555